### ISSUE TITLE
Nodejs Connector is not working with the latest Zeebe 8.0.5 version

### ISSUE THREAD

**Issue by ababneh-work** [camunda/camunda-platform-get-started#133]
Hello,

We noticed there is an issue with new clusters with the version of 8.0.5.

Can you please recommend a solutions?

Error is:
```
12:44:04.703 | zeebe |  INFO: Authenticating client with Camunda Cloud...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 13 INTERNAL: Received RST_STREAM with code 0
    at Object.callErrorFromStatus (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\client.js:190:52)
    at C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\call-stream.js:111:35
    at Object.onReceiveStatus (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\zeebe-node\dist\lib\GrpcClient.js:136:36)
    at InterceptingListenerImpl.onReceiveStatus (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\call-stream.js:106:23)
    at Object.onReceiveStatus (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
    at Object.onReceiveStatus (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\client.js:160:30)
    at ServiceClientImpl.<anonymous> (C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
    at C:\Users\*\Documents\GitHub\camunda\camunda-platform-get-started\nodejs\node_modules\zeebe-node\dist\lib\GrpcClient.js:306:47
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 13,
  details: 'Received RST_STREAM with code 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**Comment by menski** [comment]
Hey, can you provide more information how to reproduce this? Just to make sure, please ensure to update the credentials inside the source files, otherwise a exception like this will be show, as the provided credentials are not valid.

I will close this issue right now, as I assume it's related to the credentials, in case you can reproduce it and provide more information feel free to reopen the issue.

**Comment by ababneh-work** [comment]
> Hey, can you provide more information how to reproduce this? Just to make sure, please ensure to update the credentials inside the source files, otherwise a exception like this will be show, as the provided credentials are not valid.
> 
> I will close this issue right now, as I assume it's related to the credentials, in case you can reproduce it and provide more information feel free to reopen the issue.

Hello, it appears that I had to add the region to the connection parameters.

Thanks.
